### ISSUE TITLE
Runs out of memory (256MB limit)

### ISSUE THREAD

**Issue by agileware-fj** [AsylumSeekersCentre/CiviCRM-SmartGroupTag#1]
Agileware ref: SUP-6490

With a 256M memory limit, trying to run the Smarttag.updatetags API runs out of memory when attempting to process 3 smart groups with ~9700 contacts.

Each group is configured to assign a different tag.

**Comment by AsylumSeekersCentre** [comment]
I've updated the extension so that it only fetches the Contact ID when constructing the lists of Contacts, rather than fetching the whole Contact record.

In my local tests with over 11,000 Contacts in a Smart Group, memory consumption dropped from around 270MB to under 21MB.

Can you confirm whether this solves the issue?

Sorry for the slow response, my email settings were too restrictive and have been updated.

**Comment by agileware-fj** [comment]
@AsylumSeekersCentre this solves the issue and drastically increases the speed of the job.  Thanks!
